//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domvaproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class caracteristicas
    {
        public int Propiedad { get; set; }
        public bool Piscina { get; set; }
        public bool AAcondicionado { get; set; }
        public bool Barbacoa { get; set; }
        public bool VMar { get; set; }
        public bool Ascensor { get; set; }
        public bool Calefaccion { get; set; }
        public bool Garage { get; set; }
        public bool ZDeportiva { get; set; }
        public bool Jardin { get; set; }
        public bool PInfantil { get; set; }
        public bool Terraza { get; set; }
        public bool Montana { get; set; }
        public Nullable<int> Metros { get; set; }
        public Nullable<int> Baños { get; set; }
        public Nullable<int> Dormitorios { get; set; }
        public Nullable<int> DMar { get; set; }
        public bool Chimenea { get; set; }
        public bool Vendida { get; set; }
    
        public virtual propiedades propiedades { get; set; }
    }
}
