//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domvaproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class caracteristicas
    {
        public int Propiedad { get; set; }
        public Nullable<bool> Piscina { get; set; }
        public Nullable<bool> AAcondicionado { get; set; }
        public Nullable<bool> Barbacoa { get; set; }
        public Nullable<bool> VMar { get; set; }
        public Nullable<bool> Ascensor { get; set; }
        public Nullable<bool> Calefaccion { get; set; }
        public Nullable<bool> Garage { get; set; }
        public Nullable<bool> ZDeportiva { get; set; }
        public Nullable<bool> Jardin { get; set; }
        public Nullable<bool> PInfantil { get; set; }
        public Nullable<bool> Terraza { get; set; }
        public Nullable<bool> Montana { get; set; }
        public Nullable<int> Metros { get; set; }
        public Nullable<int> Baños { get; set; }
        public Nullable<int> Dormitorios { get; set; }
        public Nullable<int> DMar { get; set; }
        public Nullable<bool> Chimenea { get; set; }
        public Nullable<bool> Vendida { get; set; }
    
        public virtual propiedades propiedades { get; set; }
    }
}
