//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domvaproject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class domvaEntities : DbContext
    {
        public domvaEntities()
            : base("name=domvaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<caracteristicas> caracteristicas { get; set; }
        public DbSet<descripcionesesp> descripcionesesp { get; set; }
        public DbSet<descripcionesru> descripcionesru { get; set; }
        public DbSet<fotos> fotos { get; set; }
        public DbSet<propiedades> propiedades { get; set; }
        public DbSet<propietarios> propietarios { get; set; }
    }
}
