//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace domvaproject
{
    using System;
    using System.Collections.Generic;
    
    public partial class poblaciones
    {
        public poblaciones()
        {
            this.propiedades = new HashSet<propiedades>();
        }
    
        public string Nombre { get; set; }
        public string CodPostal { get; set; }
    
        public virtual ICollection<propiedades> propiedades { get; set; }
    }
}
